server:
  port: 8080

spring:
  application:
    name: hbooks-api
  datasource:
    url: jdbc:mariadb://localhost:6603/hbooks?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 750KB
      max-request-size: 750KB

jwt:
   secret: "your-very-secure-and-long-jwt-secret-key-at-least-32-chars" # This line and the one below must be indented!
   expiration-ms: 86400000  # 24 hours token expiry in milliseconds
